---
title: "Compare Slopes"
author: "Laura"
date: "August 9, 2016"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
require(pwr)
require(psych) 
require(Hmisc)
require(RColorBrewer)
require(plotrix)
library(rmcorr)

addalpha <- function(colors, alpha=1.0) {
    r <- col2rgb(colors, alpha=T)
    # Apply alpha
    r[4,] <- alpha*255
    r <- r/255.0
    return(rgb(r[1,], r[2,], r[3,], r[4,]))
}

```

## Different units - changes slope but does not change rmcorr
```{r, echo = FALSE, warning = FALSE}
set.seed(1)

initX <- rnorm(50)
newY <- NULL
newX <- NULL
sub <- rep(1:10, each = 5)

rsq <- .9

addx <- -2
for (i in 1:10){
    addx <- addx + .25
    tempData <- initX[sub == i] + addx
    sdx <- sd(tempData)
    sdnoise <- sdx * (sqrt((1-rsq)/rsq))
    tempy <- tempData + rnorm(5,0,sdnoise) + rnorm(1,0,3)
    newY <- c(newY, tempy)
    newX <- c(newX,tempData)
}

newX <- newX * 11
```

```{r, warning = FALSE}
newX
newY

newYtimes2 <- newY * 2
newYtimes2

mat1 <-data.frame(cbind(sub, newX, newY))
rmc1 <- rmcorr(sub, newX, newY, mat1)
rmc1$r
rmc1$model$coef[["Measure1"]]

mat2 <- data.frame(cbind(sub, newX, newYtimes2))
rmc2 <- rmcorr(sub, newX, newYtimes2, mat2)
rmc2$r
rmc2$model$coef[["Measure1"]]


```

```{r, echo = FALSE, warning = FALSE, fig.height = 6, fig.width = 12}
mypal <- colorRampPalette(RColorBrewer::brewer.pal(10,'Paired'))
cols <- mypal(10)

par(mfrow = c(1, 2), mgp = c(2.5, .75, 0), mar = c(4,4,2,1), cex = 1.2)

plot(rmc1, mat1, xlab = "x", ylab = "y", main = "rmcorr with y",
     overall = F, palette = mypal, las = 1, ylim = c(-10, 10))
text(10,-9,paste('rmcorr =', round(rmc1$r,2),'\nslope =', round(rmc1$model$coef[["Measure1"]],3)), adj = 1)

plot(rmc2, mat2, xlab = "x", ylab = "y", main = "rmcorr with y times 2",
     overall = F, palette = mypal, las = 1, ylim = c(-10, 10))
text(10,-9,paste('rmcorr =', round(rmc2$r,2),'\nslope =', round(rmc2$model$coef[["Measure1"]],3)), adj = 1)
```
